version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: warehouse
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: "/data/postgres"
    volumes:
      - postgres:/data/postgres
      - ./src/cryptobtcmonitor/postgres/01_create_exchange_table.sql:/docker-entrypoint-initdb.d/01_create_exchange_table.sql
      # - ./01_create_exchange_table.sql:/docker-entrypoint-initdb.d/01_create_exchange_table.sql
    healthcheck:
      test:
        ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 5s
      retries: 5
    restart: always
    networks:
      - postgres
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin:/var/lib/pgadmin
      # - ./docker_pgadmin_servers.json:/pgadmin4/servers.json
      - ./src/cryptobtcmonitor/postgres/docker_pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - "8080:80"
    networks:
      - postgres
    user: root
    depends_on:
      - postgres
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'postgres:5432:*:postgres:password' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    restart: always

  # pipelinerunner:
  #   image: pipelinerunner
  #   container_name: pipelinerunner
  #   build:
  #     context: ./
  #     dockerfile: ./containers/pipelinerunner/Dockerfile
  #   volumes:
  #     - ./:/code
  #   environment:
  #     WAREHOUSE_USER: ${POSTGRES_USER}
  #     WAREHOUSE_PASSWORD: ${POSTGRES_PASSWORD}
  #     WAREHOUSE_DB: ${POSTGRES_DB}
  #     WAREHOUSE_SERVER: ${POSTGRES_SERVER}
  #     WAREHOUSE_PORT: ${POSTGRES_PORT}

  # dashboard:
  #   image: metabase/metabase
  #   container_name: dashboard
  #   ports:
  #     - "3000:3000"

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
